version: '3.9'
services:
  # Main application service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - cors

  # 'cors' service
  cors:
    image: "node:14"
    command: "npm install cors && tail -f /dev/null"